[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../starksheet-cairo"

[context.production]
  environment = { REACT_APP_NETWORK = "mainnet" }

[context.testnet]
  environment = { REACT_APP_NETWORK = "goerli" }

[context.deploy-preview]
  environment = { REACT_APP_NETWORK = "goerli" }
